### ISSUE TITLE
Step 8

### ISSUE THREAD

**Issue by abantecart** [sirinibin/laravel-5.5-lumen-5.5-with-OAuth2#1]
Is there an issue in step 8?
I try to follow instruction and it looks like there infinitive loop here :)  if you repeat step #8.
**Step8. cd developers and run step3-8 once again.**
Should it be 3 - 7 ?

In step 3, my guess that database name will be different. Correct? 
If I run step 7 inside of developers directory, autoloader is missing. How should this be ran? 

Thank you

**Comment by sirinibin** [comment]
@abantecart: sorry its a mistake.  its to cd developers & run composer install then repeat step4,5 & 6. i have made the correction but the database is still same. you don't need to make a new one.
you can simply cd to developer folder and run composer install
-Thanks for reporting

**Comment by abantecart** [comment]
Thank you
