### ISSUE TITLE
$ php artisan key:generate - Error

### ISSUE THREAD

**Issue by i-coder** [sirinibin/laravel-5.5-lumen-5.5-with-OAuth2#2]
$ php artisan key:generate

[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "key" namespace.

**Comment by webeindustry** [comment]
there's no vendor directory. this doesn't work as is

**Comment by ghost** [comment]
It's just a random 32 bit key
I did `php -r "echo md5(uniqid()).\"\n\";"`
and put that in `.env` file for `APP_KEY`
