### ISSUE TITLE
[Question] How does password reset work?

### ISSUE THREAD

**Issue by dpskipper** [sirinibin/laravel-5.5-lumen-5.5-with-OAuth2#4]
Hi,
Lovely API you've set up here.. Just a quick question, how do I reset a user password?

If i use the PUT /users/{id} endpoint, and send all the correct data, when i set the password in the body as differnet to what exists in the database, the hash does not update, and I can still use the old password. Why is the password a requirement in the route to update user info?

**Comment by sirinibin** [comment]
@dpskipper thanks for reporting this. i have made a fix for this.Now  you can use the user update action to reset password and the password parameter is not mandatory for it as long as you have the access token for the request to authenticate.
Let me know if you have any questions. thanks

**Comment by dpskipper** [comment]
:+1: Thanks @sirinibin
