### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by dpskipper** [sirinibin/laravel-5.5-lumen-5.5-with-OAuth2#5]
Hi @sirinibin,
I've been poking around your API some more, and I have a suggestion to make. From the other APIs i've worked on, it is standard practice that when a user resets their password, their current access token gets revoked and they have to re-authenticate to obtain a new one... If this does not happen, a user might have their password stolen, and an attacker could have API access, and the user cannot stop them from further harming their account, because a password reset will not revoke the compromised access token.

It would be great, if you could delete the authorize token and access token from the database when a user changes their password...

Also, on another note. How do I change the UserController, so that I can update any field without making all the others null? For example if I wish to only change the `username` and not `email`, in the body request, Example: ```{
	"username": "bob1@me.com,
	"password": "1234"
}```

This JSON PUT will override the  `email` field in the database to null.

Thanks!

**Comment by sirinibin** [comment]
@dpskipper : thanks for reporting this. now it will send you an additional field "new_access_token" in the response of update action for user Controller iff you change the password.
the e-mail null issue is also fixed. please verify it . thanks
