### ISSUE TITLE
[Bug] Access Token not needed for: GET /employees

### ISSUE THREAD

**Issue by dpskipper** [sirinibin/laravel-5.5-lumen-5.5-with-OAuth2#6]
In your online documentation the example has an Access Token specified in the header. This token is not actually used as making the API call to /employees will return the data and 200 OK without any token in the header at all.

Is this intentional?

**Comment by sirinibin** [comment]
It's optional. Either you can pass in header or as a GET param.

**Comment by sirinibin** [comment]
@dpskipper that you can control here 
 public function __construct(Request $request)
    {
        $this->middleware('auth',['except'=>['index','view']]);

    }
if you want to add access token authentication for index & view actions then just remove them from the except array. thanks
